version: "3"
services:
  spbt-dev:
    image: spbt-dev
    hostname: spbt-dev
    container_name: spbt-dev
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.dev
    working_dir: /build
    volumes:
      - .:/build
    env_file:
      - ./.env
    environment:
      ENVRONMENT: "dev"
    restart: unless-stopped
    ports:
      - 9002:9002
    depends_on:
      - "spbt-redis"

  spbt-prod:
    image: spbt-prod
    hostname: spbt-prod
    container_name: spbt-prod
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile
    env_file:
      - ./.env
    environment:
      ENVRONMENT: "prod"
    restart: unless-stopped
    ports:
      - 8082:8082
    depends_on:
      - "spbt-redis"
